### ISSUE TITLE
中文字体报错

### ISSUE THREAD

**Issue by xu8117** [tony-xlh/searchablePDF4j#1]
```
Exception in thread "main" java.lang.IllegalArgumentException: U+6C83 ('.notdef') is not available in the font Courier, encoding: WinAnsiEncoding
	at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:410)
	at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:337)
	at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:368)
	at com.tonyxlh.searchablePDF4j.SearchablePDFCreator.calculateFontSize(SearchablePDFCreator.java:151)
	at com.tonyxlh.searchablePDF4j.SearchablePDFCreator.addTextOverlay(SearchablePDFCreator.java:140)
	at com.tonyxlh.searchablePDF4j.SearchablePDFCreator.addTextOverlay(SearchablePDFCreator.java:124)
	at com.tonyxlh.searchablePDF4j.SearchablePDFCreator.addPage(SearchablePDFCreator.java:95)
	at com.tonyxlh.searchablePDF4j.SearchablePDFCreator.addPage(SearchablePDFCreator.java:103)
	at com.tonyxlh.searchablePDF4j.SearchablePDFCreator.create(SearchablePDFCreator.java:38)
	at com.tonyxlh.searchablePDF4j.Main.main(Main.java:23)
```

![image](https://github.com/user-attachments/assets/e1bfd766-e7d4-471d-a9b9-58f152106869)

检查了代码，支持的字体包括
```
public enum FontName
    {
        TIMES_ROMAN("Times-Roman"), //
        TIMES_BOLD("Times-Bold"), //
        TIMES_ITALIC("Times-Italic"), //
        TIMES_BOLD_ITALIC("Times-BoldItalic"), //
        HELVETICA("Helvetica"), //
        HELVETICA_BOLD("Helvetica-Bold"), //
        HELVETICA_OBLIQUE("Helvetica-Oblique"), //
        HELVETICA_BOLD_OBLIQUE("Helvetica-BoldOblique"), //
        COURIER("Courier"), //
        COURIER_BOLD("Courier-Bold"), //
        COURIER_OBLIQUE("Courier-Oblique"), //
        COURIER_BOLD_OBLIQUE("Courier-BoldOblique"), //
        SYMBOL("Symbol"), //
        ZAPF_DINGBATS("ZapfDingbats");
        ...
    }
```
这些字体都不支持中文，有什么解决办法吗

**Comment by xulihang** [comment]
可以加载外部字体，代码见这里：https://github.com/xulihang/jPDFBox/blob/e858973c4d1028bd6cf12c4c23fe66617b8dc301/src/main/java/pdfbox/SearchablePDFCreator.java#L13

**Comment by xu8117** [comment]
感谢，我也刚找到方法
